### PR TITLE
Change get_run_date function to get the date corresponding to a given…

### PR DESCRIPTION
**Pull request by marialainez**
… run more efficiently. Solves issue #143

### CODE REVIEW

**Comment by morcuended** [comment]
thanks @marialainez. Let me have a look

**Comment by contrera** [comment]
What happens in this new scheme if the run in not in the merged_run_summaries_file.
Does it have to be included beforehand?

**Comment by morcuended** [comment]
It'll fail if a run is not present in the merged summary. A cronjob will update the merged file every day with the new runs from that date. Alternatively, we can assume by default that if a run is not in the merged file, the date is the one given as input in the sequencer/closer. What do you think?

**Comment by contrera** [comment]
It is fine. I would suggest to do both both:  If the run is not in the merged summary --> output a warning and use the date provided.

**Comment by morcuended** [comment]
@marialainez, can you try to implement that. Something like:

```python
try:
    [current piece of code]
except IndexError:
    log.warning(
        f'Run {run_id} not found in the summary table. Assuming the date {options.date}'
    )
    date_string = options.date (in YYYYMMDD format)
```

**Comment by marialainez** [comment]
yes, done in #153

**Pull request merged**
