### PR TITLE
Use first event time in update catalog script

### LINKED ISSUE #262: Wrong run_start values in source catalog for runs taken with EVBv6

### PR DESCRIPTION
**Pull request by morcuended**
Also some cleanup is done.

Closes #262

### CODE REVIEW

**Review by marialainez — COMMENTED** [review]
Isn't the format and scale of the dragon_time the same as that of the times in the run_start column?

**Comment by morcuended** [comment]
> Isn't the format and scale of the dragon_time the same as that of the times in the run_start column?

good point, I would have to check again

**Comment by morcuended** [comment]
> Isn't the format and scale of the dragon_time the same as that of the times in the run_start column?
No, run_start in the summary was defined like
```
run_start = int(round(Time(f.camera_config.date, format="unix").unix_tai)) * int(1e9)
```
The proper way of getting the eventwise timestamps from `dragon_time` is using `time = (timestamp, format="unix", scale="utc")`. Then, getting the ISO format in UTC scale as `time.utc.iso` (to make sure to use UTC scale). So I think it is fine as it is now

**Comment by morcuended** [comment]
To make the tests pass you need to merge the current main version to force the usage of lstchain >=v0.10.5

**Review by marialainez — APPROVED** [review]

**Pull request merged**
